name: Run Facebook ChatGPT Bot

on: [push]

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm install
    - run: node index.js
      env:
        FB_EMAIL: ${{ secrets.FB_EMAIL }}
        FB_PASSWORD: ${{ secrets.FB_PASSWORD }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
